version: '3'

services:
    mongodb:
        image: mongo:3.6-jessie
        container_name: "mongodb"
        restart: unless-stopped
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
          - MONGODB_USER="user"
          - MONGODB_PASS="pass"
        volumes:
          - /c/YourDockerFilesFolder/mongo/data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet